export const TYPES= {
    ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
    REMOVE_ONE_FROM_FAVORITE: "REMOVE_ONE_FROM_FAVORITE",
    REMOVE_ALL_FROM_FAVORITE: "REMOVE_ALL_FROM_FAVORITE",
    CLEAR_FAVORITE: "CLEAR_FAVORITE"
};

